services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: trainer
    ports: ["5432:5432"]  # si 5432 está ocupado, usa "5433:5432"
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes:
  pgdata:
